# Задание к занятию 6.1: Введение в обработку текста

## 1. Чтение текстов, нужных для упражнений

In [1]:
import numpy as np
import pandas as pd

In [2]:
negative = pd.read_csv('negative.csv',delimiter=";")
positive = pd.read_csv('positive.csv',delimiter=";")

In [3]:
negative.shape

(111923, 12)

In [4]:
negative.head()

tid       tdate            tmane  \
0  408906762813579264  1386325944  dugarchikbellko   
1  408906818262687744  1386325957     nugemycejela   
2  408906858515398656  1386325966          4post21   
3  408906914437685248  1386325980         Poliwake   
4  408906914723295232  1386325980       capyvixowe   

                                               ttext  ttype  trep  trtw  tfav  \
0  на работе был полный пиддес :| и так каждое за...     -1     0     0     0   
1  Коллеги сидят рубятся в Urban terror, а я из-з...     -1     0     0     0   
2  @elina_4post как говорят обещаного три года жд...     -1     0     0     0   
3  Желаю хорошего полёта и удачной посадки,я буду...     -1     0     0     0   
4  Обновил за каким-то лешим surf, теперь не рабо...     -1     0     0     0   

   tstcount  tfol  tfrien  listcount  
0      8064   111      94          2  
1        26    42      39          0  
2       718    49     249          0  
3     10628   207     200          0  
4        35    17      34          0

In [5]:
positive.shape

(114911, 12)

In [6]:
positive.head()

tid       tdate            tmane  \
0  408906692374446080  1386325927  pleease_shut_up   
1  408906692693221377  1386325927  alinakirpicheva   
2  408906695083954177  1386325927        EvgeshaRe   
3  408906695356973056  1386325927    ikonnikova_21   
4  408906761416867842  1386325943        JumpyAlex   

                                               ttext  ttype  trep  trtw  tfav  \
0  @first_timee хоть я и школота, но поверь, у на...      1     0     0     0   
1  Да, все-таки он немного похож на него. Но мой ...      1     0     0     0   
2  RT @KatiaCheh: Ну ты идиотка) я испугалась за ...      1     0     1     0   
3  RT @digger2912: "Кто то в углу сидит и погибае...      1     0     1     0   
4  @irina_dyshkant Вот что значит страшилка :D\nН...      1     0     0     0   

   tstcount  tfol  tfrien  listcount  
0      7569    62      61          0  
1     11825    59      31          2  
2      1273    26      27          0  
3      1549    19      17          0  
4       597    16      23          1

In [7]:
alltwits = pd.concat([positive, negative]).sample(frac=1).reset_index(drop=True)
alltwits.shape

(226834, 12)

In [8]:
alltwits.head()

tid       tdate            tmane  \
0  409826950501662720  1386545333       Royal_Lena   
1  409069272682745856  1386364689        Semen_msv   
2  419406066074796032  1388829173  annavinokurova4   
3  409307824272179200  1386421564   IrinaMikheeva1   
4  409850441137410048  1386550934          yszka50   

                                               ttext  ttype  trep  trtw  tfav  \
0  @u2barmaley что бы вам не было обидно,что я не...      1     0     0     0   
1  @rtgfus а кстати Саня с днюхой тебя! Немного п...      1     0     0     0   
2  Блин коньки то дома, а не у бабушки:/ ок поеду...     -1     0     0     0   
3  И завтра должен решиться вопрос о НГ, эх надеж...      1     0     0     0   
4  писать расписание в дневнике, не заглядывая на...      1     0     0     0   

   tstcount  tfol  tfrien  listcount  
0      5810    83      58          1  
1      2784   111     118          5  
2      1822    36      48          0  
3     59017   253     136          3  
4     30023   769      34          0

In [9]:
alltwits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226834 entries, 0 to 226833
Data columns (total 12 columns):
tid          226834 non-null int64
tdate        226834 non-null int64
tmane        226834 non-null object
ttext        226834 non-null object
ttype        226834 non-null int64
trep         226834 non-null int64
trtw         226834 non-null int64
tfav         226834 non-null int64
tstcount     226834 non-null int64
tfol         226834 non-null int64
tfrien       226834 non-null int64
listcount    226834 non-null int64
dtypes: int64(10), object(2)
memory usage: 20.8+ MB


In [10]:
alltwits['ttype'].unique()

array([ 1, -1], dtype=int64)

In [11]:
y = (alltwits['ttype'] + 1) / 2
y.unique()

array([ 1.,  0.])

In [12]:
from sklearn.model_selection import train_test_split
y_train, y_val, x_train, x_val = train_test_split(y, alltwits.drop(['ttype'], axis=1), test_size=0.2, random_state=42)
x_train.head()

tid       tdate         tmane  \
107097  423002260038496256  1389686572  Tarantinka24   
224163  409986075856502784  1386583272   qanofecyzoh   
63992   413477085538439168  1387415593    serzh_love   
108549  409432457000517632  1386451279   Nata_Marino   
67962   414818085569568768  1387735313  belitskaya_e   

                                                    ttext  trep  trtw  tfav  \
107097  RT @achekhova: Посмотрела фильм "Ёлки". Понрав...     0    41     0   
224163  а давно мой сайт сдох? может кто-то следил))) ...     0     0     0   
63992   Я уже и не знаю, ко скольки я приеду сегодня( ...     0     0     0   
108549  Мс Маша и Наташа !!))) что твориться .. Что тв...     0     0     0   
67962   @kosov_kv удивительно, я с пять вечера пытаюсь...     0     0     0   

        tstcount  tfol  tfrien  listcount  
107097         7     4      12          0  
224163       163   134     147          0  
63992       1806    27      32          0  
108549      3443    89      75          0  
67962       7837   263     136          6

In [13]:
y_train.head()

107097    0.0
224163    1.0
63992     0.0
108549    1.0
67962     0.0
Name: ttype, dtype: float64

In [14]:
x_val.head()

tid       tdate            tmane  \
215081  424293457596014593  1389994417         hug_theo   
220754  415725524271366144  1387951663           fcuktv   
60463   409504829523103744  1386468534   xeqagybicibyti   
213263  415155820171890688  1387815835  Natalie_Torres9   
113055  409969702329667584  1386579368  Admiral_Raccoon   

                                                    ttext  trep  trtw  tfav  \
215081  @longtimelie дорогая, ты до сих пор учишься? а...     0     0     0   
220754  @molodo_zeleno неизвестно( там 14 этаж, следов...     0     0     0   
60463   кого на фейсбуке 74 братьев и сестер,обьесни к...     0     0     0   
213263  Тогда еще совсем малышами были...скучаю по мал...     0     0     0   
113055  RT @enterdasha: ФАНДОМИЩЕ А7Х, нужен кому мета...     0     1     0   

        tstcount  tfol  tfrien  listcount  
215081     47523   586     350          9  
220754     62441  1543     482         52  
60463        447   191     187          0  
213263      1172    16      18          1  
113055     24486   277     258          3

In [15]:
y_val.head()

215081    0.0
220754    0.0
60463     0.0
213263    0.0
113055    1.0
Name: ttype, dtype: float64

## 2. Строим частотный список

In [34]:
import re
import collections

def get_freq_list(texts):
    words = collections.defaultdict(int)
    for text in texts:
        for word in re.split(r'\W', text):
            words[word] += 1
    del words[u'']
    
    return [(word, words[word]) for word in sorted(words, key=lambda w: words[w], reverse=True)]

In [37]:
get_freq_list(x_train['ttext'])

[('не', 55817),
 ('и', 44252),
 ('я', 42665),
 ('в', 42272),
 ('RT', 30395),
 ('на', 28654),
 ('что', 27048),
 ('t', 26643),
 ('http', 26495),
 ('co', 26492),
 ('с', 21986),
 ('а', 21763),
 ('меня', 16469),
 ('то', 16110),
 ('как', 15555),
 ('у', 15128),
 ('D', 13998),
 ('так', 13601),
 ('это', 13546),
 ('мне', 13156),
 ('все', 12206),
 ('ты', 10841),
 ('но', 10411),
 ('Я', 10166),
 ('по', 9591),
 ('за', 9179),
 ('уже', 8124),
 ('же', 7764),
 ('А', 7208),
 ('ну', 7205),
 ('только', 6531),
 ('бы', 6490),
 ('еще', 6253),
 ('да', 6198),
 ('вот', 6025),
 ('тебя', 5838),
 ('нет', 5829),
 ('когда', 5612),
 ('из', 5400),
 ('к', 5351),
 ('очень', 5324),
 ('день', 5202),
 ('будет', 5110),
 ('сегодня', 5101),
 ('хочу', 4933),
 ('просто', 4886),
 ('он', 4867),
 ('от', 4492),
 ('3', 4419),
 ('И', 4381),
 ('тебе', 4374),
 ('было', 4343),
 ('мы', 4339),
 ('тоже', 4114),
 ('там', 3802),
 ('до', 3782),
 ('даже', 3766),
 ('надо', 3753),
 ('его', 3740),
 ('вообще', 3702),
 ('о', 3648),
 ('теперь', 3609)

## 3. Bag of words

### 3.1. CountVectorizer

In [38]:
import sklearn.feature_extraction.text

In [39]:
vctr = sklearn.feature_extraction.text.CountVectorizer()

In [40]:
X_train_counts = vctr.fit_transform(x_train["ttext"])

In [41]:
X_train_counts.shape

(181467, 254632)

In [42]:
vctr

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [43]:
vctr.vocabulary_

{'rt': 78589,
 'achekhova': 9356,
 'посмотрела': 198983,
 'фильм': 241100,
 'ёлки': 254001,
 'понравился': 197517,
 'но': 176631,
 'моей': 167201,
 'жизни': 138380,
 'бумеранг': 114646,
 'добра': 133019,
 'не': 173316,
 'работает': 208528,
 'всё': 121987,
 'чаще': 246950,
 'прихожу': 203919,
 'выводу': 122582,
 'делай': 130801,
 'давно': 129370,
 'мой': 167305,
 'сайт': 215326,
 'сдох': 217342,
 'может': 167224,
 'кто': 157573,
 'то': 232121,
 'следил': 220452,
 'похоже': 200114,
 'днс': 132870,
 'помер': 197018,
 'уже': 236743,
 'знаю': 145366,
 'ко': 153204,
 'скольки': 219740,
 'приеду': 202623,
 'сегодня': 217465,
 'купите': 157986,
 'мне': 166858,
 'вертолёт': 117179,
 'мс': 168304,
 'маша': 164559,
 'наташа': 172639,
 'что': 248251,
 'твориться': 230612,
 'kosov_kv': 50249,
 'удивительно': 236427,
 'пять': 208392,
 'вечера': 117488,
 'пытаюсь': 208136,
 'открыть': 184446,
 'чтоб': 248253,
 'пост': 199128,
 'написать': 171505,
 'ну': 177511,
 'нет': 175610,
 'так': 229529,
 'днем'

In [44]:
vctr.vocabulary_.get('мимими')

166233

### 3.2. TF.IDF vectorizer

In [45]:
vctr_tfidf = sklearn.feature_extraction.text.TfidfTransformer()

In [46]:
X_train_counts_tfidf = vctr_tfidf.fit_transform(X_train_counts)

In [47]:
vctr_tfidf.idf_

array([  6.9863418 ,   8.37263616,  11.31707514, ...,  11.72254025,
        11.72254025,  12.41568743])

In [48]:
vctr_tfidf.get_params()

{'norm': 'l2', 'smooth_idf': True, 'sublinear_tf': False, 'use_idf': True}

In [49]:
import sklearn.pipeline
import sklearn.naive_bayes

text_clf = sklearn.pipeline.Pipeline([('vect', sklearn.feature_extraction.text.CountVectorizer()),
                     ('clf', sklearn.naive_bayes.MultinomialNB())])

In [50]:
text_clf

Pipeline(steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

## 4. Classifying

In [51]:
text_clf.fit(x_train["ttext"], y_train)

Pipeline(steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [52]:
predicted = text_clf.predict(x_val["ttext"])

In [53]:
import sklearn.metrics
print(sklearn.metrics.classification_report(y_val, predicted, target_names=["negative", "positive"]))

             precision    recall  f1-score   support

   negative       0.74      0.79      0.76     22381
   positive       0.78      0.72      0.75     22986

avg / total       0.76      0.76      0.76     45367



In [54]:
sklearn.metrics.confusion_matrix(y_val, predicted)

array([[17719,  4662],
       [ 6342, 16644]])